import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PeriodicTable extends StatelessWidget {
  const PeriodicTable({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black87,
      body: Center(
        child: InteractiveViewer(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text(
              'Abdul Moiz',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
              const Row(
                children: [
                  ElementBox(
                    atomicNumber: '1',
                    color: Colors.green,
                    elementSymbol: 'H',
                    elementName: 'Hydrogen',
                    atomicMass: '1.008',
                  ),
                  Spacer(),
                  ElementBox(
                    atomicNumber: '2',
                    color: Colors.blue,
                    elementSymbol: 'He',
                    elementName: 'Helium',
                    atomicMass: '4.0026',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '3',
                    color: Colors.orange.shade400,
                    elementSymbol: 'Li',
                    elementName: 'Lithium',
                    atomicMass: '6.94',
                  ),
                  const ElementBox(
                    atomicNumber: '4',
                    color: Colors.yellow,
                    elementSymbol: 'Be',
                    elementName: 'Beryllium',
                    atomicMass: '9.0122',
                  ),
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '5',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'B',
                    elementName: 'Boron',
                    atomicMass: '10.81',
                  ),
                  ElementBox(
                    atomicNumber: '6',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'C',
                    elementName: 'Carbon',
                    atomicMass: '12.011',
                  ),
                  ElementBox(
                    atomicNumber: '7',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'N',
                    elementName: 'Nitrogen',
                    atomicMass: '14.007',
                  ),
                  ElementBox(
                    atomicNumber: '8',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'O',
                    elementName: 'Oxygen',
                    atomicMass: '15.999',
                  ),
                  ElementBox(
                    atomicNumber: '9',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'F',
                    elementName: 'Fluorine',
                    atomicMass: '18.998',
                  ),
                  const ElementBox(
                    atomicNumber: '10',
                    color: Colors.blue,
                    elementSymbol: 'Ne',
                    elementName: 'Neon',
                    atomicMass: '20.180',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '11',
                    color: Colors.orange.shade400,
                    elementSymbol: 'Na',
                    elementName: 'Sodium',
                    atomicMass: '22.99',
                  ),
                  const ElementBox(
                    atomicNumber: '12',
                    color: Colors.yellow,
                    elementSymbol: 'Mg',
                    elementName: 'Magnesium',
                    atomicMass: '24.305',
                  ),
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '13',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Al',
                    elementName: 'Aluminium',
                    atomicMass: '26.982',
                  ),
                  ElementBox(
                    atomicNumber: '14',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'Si',
                    elementName: 'Silicon',
                    atomicMass: '28.085',
                  ),
                  ElementBox(
                    atomicNumber: '15',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'P',
                    elementName: 'Phosphorus',
                    atomicMass: '30.974',
                  ),
                  ElementBox(
                    atomicNumber: '16',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'S',
                    elementName: 'Sulfur',
                    atomicMass: '32.06',
                  ),
                  ElementBox(
                    atomicNumber: '17',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'Cl',
                    elementName: 'Chlorine',
                    atomicMass: '35.45',
                  ),
                  const ElementBox(
                    atomicNumber: '18',
                    color: Colors.blue,
                    elementSymbol: 'Ar',
                    elementName: 'Argon',
                    atomicMass: '39.948',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '19',
                    color: Colors.orange.shade400,
                    elementSymbol: 'K',
                    elementName: 'Potassium',
                    atomicMass: '39.098',
                  ),
                  const ElementBox(
                    atomicNumber: '20',
                    color: Colors.yellow,
                    elementSymbol: 'Ca',
                    elementName: 'Calcium',
                    atomicMass: '40.078',
                  ),
                  ElementBox(
                    atomicNumber: '21',
                    color: Colors.red.shade300,
                    elementSymbol: 'Sc',
                    elementName: 'Scandium',
                    atomicMass: '44.956',
                  ),
                  ElementBox(
                    atomicNumber: '22',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ti',
                    elementName: 'Titanium',
                    atomicMass: '47.867',
                  ),
                  ElementBox(
                    atomicNumber: '23',
                    color: Colors.red.shade300,
                    elementSymbol: 'V',
                    elementName: 'Vanadium',
                    atomicMass: '50.942',
                  ),
                  ElementBox(
                    atomicNumber: '24',
                    color: Colors.red.shade300,
                    elementSymbol: 'Cr',
                    elementName: 'Chromium',
                    atomicMass: '51.996',
                  ),
                  ElementBox(
                    atomicNumber: '25',
                    color: Colors.red.shade300,
                    elementSymbol: 'Mn',
                    elementName: 'Manganese',
                    atomicMass: '54.938',
                  ),
                  ElementBox(
                    atomicNumber: '26',
                    color: Colors.red.shade300,
                    elementSymbol: 'Fe',
                    elementName: 'Iron',
                    atomicMass: '55.845',
                  ),
                  ElementBox(
                    atomicNumber: '27',
                    color: Colors.red.shade300,
                    elementSymbol: 'Co',
                    elementName: 'Cobalt',
                    atomicMass: '58.933',
                  ),
                  ElementBox(
                    atomicNumber: '28',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ni',
                    elementName: 'Nickel',
                    atomicMass: '58.693',
                  ),
                  ElementBox(
                    atomicNumber: '29',
                    color: Colors.red.shade300,
                    elementSymbol: 'Cu',
                    elementName: 'Copper',
                    atomicMass: '63.546',
                  ),
                  ElementBox(
                    atomicNumber: '30',
                    color: Colors.red.shade300,
                    elementSymbol: 'Zn',
                    elementName: 'Zinc',
                    atomicMass: '65.38',
                  ),
                  ElementBox(
                    atomicNumber: '31',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Ga',
                    elementName: 'Gallium',
                    atomicMass: '69.723',
                  ),
                  ElementBox(
                    atomicNumber: '32',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'Ge',
                    elementName: 'Germanium',
                    atomicMass: '72.63',
                  ),
                  ElementBox(
                    atomicNumber: '33',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'As',
                    elementName: 'Arsenic',
                    atomicMass: '74.922',
                  ),
                  ElementBox(
                    atomicNumber: '34',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'Se',
                    elementName: 'Selenium',
                    atomicMass: '78.971',
                  ),
                  ElementBox(
                    atomicNumber: '35',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'Br',
                    elementName: 'Bromine',
                    atomicMass: '79.904',
                  ),
                  const ElementBox(
                    atomicNumber: '36',
                    color: Colors.blue,
                    elementSymbol: 'Kr',
                    elementName: 'Krypton',
                    atomicMass: '83.798',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '37',
                    color: Colors.orange.shade400,
                    elementSymbol: 'Rb',
                    elementName: 'Rubidium',
                    atomicMass: '85.468',
                  ),
                  const ElementBox(
                    atomicNumber: '38',
                    color: Colors.yellow,
                    elementSymbol: 'Sr',
                    elementName: 'Strontium',
                    atomicMass: '87.62',
                  ),
                  ElementBox(
                    atomicNumber: '39',
                    color: Colors.red.shade300,
                    elementSymbol: 'Y',
                    elementName: 'Yttrium',
                    atomicMass: '88.906',
                  ),
                  ElementBox(
                    atomicNumber: '40',
                    color: Colors.red.shade300,
                    elementSymbol: 'Zr',
                    elementName: 'Zirconium',
                    atomicMass: '91.224',
                  ),
                  ElementBox(
                    atomicNumber: '41',
                    color: Colors.red.shade300,
                    elementSymbol: 'Nb',
                    elementName: 'Niobium',
                    atomicMass: '92.906',
                  ),
                  ElementBox(
                    atomicNumber: '42',
                    color: Colors.red.shade300,
                    elementSymbol: 'Mo',
                    elementName: 'Molybdenum',
                    atomicMass: '95.95',
                  ),
                  ElementBox(
                    atomicNumber: '43',
                    color: Colors.red.shade300,
                    elementSymbol: 'Tc',
                    elementName: 'Technetium',
                    atomicMass: '98',
                  ),
                  ElementBox(
                    atomicNumber: '44',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ru',
                    elementName: 'Ruthenium',
                    atomicMass: '101.07',
                  ),
                  ElementBox(
                    atomicNumber: '45',
                    color: Colors.red.shade300,
                    elementSymbol: 'Rh',
                    elementName: 'Rhodium',
                    atomicMass: '102.91',
                  ),
                  ElementBox(
                    atomicNumber: '46',
                    color: Colors.red.shade300,
                    elementSymbol: 'Pd',
                    elementName: 'Palladium',
                    atomicMass: '106.42',
                  ),
                  ElementBox(
                    atomicNumber: '47',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ag',
                    elementName: 'Silver',
                    atomicMass: '107.87',
                  ),
                  ElementBox(
                    atomicNumber: '48',
                    color: Colors.red.shade300,
                    elementSymbol: 'Cd',
                    elementName: 'Cadmium',
                    atomicMass: '112.41',
                  ),
                  ElementBox(
                    atomicNumber: '49',
                    color: Colors.blue.shade100,
                    elementSymbol: 'In',
                    elementName: 'Indium',
                    atomicMass: '114.82',
                  ),
                  ElementBox(
                    atomicNumber: '50',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Sn',
                    elementName: 'Tin',
                    atomicMass: '118.71',
                  ),
                  ElementBox(
                    atomicNumber: '51',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'Sb',
                    elementName: 'Antimony',
                    atomicMass: '121.76',
                  ),
                  ElementBox(
                    atomicNumber: '52',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'Te',
                    elementName: 'Tellurium',
                    atomicMass: '127.60',
                  ),
                  ElementBox(
                    atomicNumber: '53',
                    color: Colors.greenAccent.shade400,
                    elementSymbol: 'I',
                    elementName: 'Iodine',
                    atomicMass: '126.90',
                  ),
                  const ElementBox(
                    atomicNumber: '54',
                    color: Colors.blue,
                    elementSymbol: 'Xe',
                    elementName: 'Xenon',
                    atomicMass: '131.29',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '55',
                    color: Colors.orange.shade400,
                    elementSymbol: 'Cs',
                    elementName: 'Cesium',
                    atomicMass: '132.91',
                  ),
                  const ElementBox(
                    atomicNumber: '56',
                    color: Colors.yellow,
                    elementSymbol: 'Ba',
                    elementName: 'Barium',
                    atomicMass: '137.33',
                  ),
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '72',
                    color: Colors.red.shade300,
                    elementSymbol: 'Hf',
                    elementName: 'Hafnium',
                    atomicMass: '178.49',
                  ),
                  ElementBox(
                    atomicNumber: '73',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ta',
                    elementName: 'Tantalum',
                    atomicMass: '180.95',
                  ),
                  ElementBox(
                    atomicNumber: '74',
                    color: Colors.red.shade300,
                    elementSymbol: 'W',
                    elementName: 'Tungsten',
                    atomicMass: '183.84',
                  ),
                  ElementBox(
                    atomicNumber: '75',
                    color: Colors.red.shade300,
                    elementSymbol: 'Re',
                    elementName: 'Rhenium',
                    atomicMass: '186.21',
                  ),
                  ElementBox(
                    atomicNumber: '76',
                    color: Colors.red.shade300,
                    elementSymbol: 'Os',
                    elementName: 'Osmium',
                    atomicMass: '190.23',
                  ),
                  ElementBox(
                    atomicNumber: '77',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ir',
                    elementName: 'Iridium',
                    atomicMass: '192.22',
                  ),
                  ElementBox(
                    atomicNumber: '78',
                    color: Colors.red.shade300,
                    elementSymbol: 'Pt',
                    elementName: 'Platinum',
                    atomicMass: '195.08',
                  ),
                  ElementBox(
                    atomicNumber: '79',
                    color: Colors.red.shade300,
                    elementSymbol: 'Au',
                    elementName: 'Gold',
                    atomicMass: '196.97',
                  ),
                  ElementBox(
                    atomicNumber: '80',
                    color: Colors.red.shade300,
                    elementSymbol: 'Hg',
                    elementName: 'Mercury',
                    atomicMass: '200.59',
                  ),
                  ElementBox(
                    atomicNumber: '81',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Tl',
                    elementName: 'Thallium',
                    atomicMass: '204.38',
                  ),
                  ElementBox(
                    atomicNumber: '82',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Pb',
                    elementName: 'Lead',
                    atomicMass: '207.2',
                  ),
                  ElementBox(
                    atomicNumber: '83',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Bi',
                    elementName: 'Bismuth',
                    atomicMass: '208.98',
                  ),
                  ElementBox(
                    atomicNumber: '84',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Po',
                    elementName: 'Polonium',
                    atomicMass: '209',
                  ),
                  ElementBox(
                    atomicNumber: '85',
                    color: Colors.greenAccent.shade200,
                    elementSymbol: 'At',
                    elementName: 'Astatine',
                    atomicMass: '210',
                  ),
                  const ElementBox(
                    atomicNumber: '86',
                    color: Colors.blue,
                    elementSymbol: 'Rn',
                    elementName: 'Radon',
                    atomicMass: '222',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '87',
                    color: Colors.orange.shade400,
                    elementSymbol: 'Fr',
                    elementName: 'Francium',
                    atomicMass: '223',
                  ),
                  const ElementBox(
                    atomicNumber: '88',
                    color: Colors.yellow,
                    elementSymbol: 'Ra',
                    elementName: 'Radium',
                    atomicMass: '226',
                  ),
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '104',
                    color: Colors.red.shade300,
                    elementSymbol: 'Rf',
                    elementName: 'Rutherfordium',
                    atomicMass: '267',
                  ),
                  ElementBox(
                    atomicNumber: '105',
                    color: Colors.red.shade300,
                    elementSymbol: 'Db',
                    elementName: 'Dubnium',
                    atomicMass: '270',
                  ),
                  ElementBox(
                    atomicNumber: '106',
                    color: Colors.red.shade300,
                    elementSymbol: 'Sg',
                    elementName: 'Seaborgium',
                    atomicMass: '271',
                  ),
                  ElementBox(
                    atomicNumber: '107',
                    color: Colors.red.shade300,
                    elementSymbol: 'Bh',
                    elementName: 'Bohrium',
                    atomicMass: '270',
                  ),
                  ElementBox(
                    atomicNumber: '108',
                    color: Colors.red.shade300,
                    elementSymbol: 'Hs',
                    elementName: 'Hassium',
                    atomicMass: '277',
                  ),
                  ElementBox(
                    atomicNumber: '109',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Mt',
                    elementName: 'Meitnerium',
                    atomicMass: '276',
                  ),
                  ElementBox(
                    atomicNumber: '110',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Ds',
                    elementName: 'Darmstadtium',
                    atomicMass: '281',
                  ),
                  ElementBox(
                    atomicNumber: '111',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Rg',
                    elementName: 'Roentgenium',
                    atomicMass: '280',
                  ),
                  ElementBox(
                    atomicNumber: '112',
                    color: Colors.red.shade300,
                    elementSymbol: 'Cn',
                    elementName: 'Copernicium',
                    atomicMass: '285',
                  ),
                  ElementBox(
                    atomicNumber: '113',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Nh',
                    elementName: 'Nihonium',
                    atomicMass: '284',
                  ),
                  ElementBox(
                    atomicNumber: '114',
                    color: Colors.blue.shade100,
                    elementSymbol: 'Fl',
                    elementName: 'Flerovium',
                    atomicMass: '289',
                  ),
                  ElementBox(
                    atomicNumber: '115',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Mc',
                    elementName: 'Moscovium',
                    atomicMass: '288',
                  ),
                  ElementBox(
                    atomicNumber: '116',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Lv',
                    elementName: 'Livermorium',
                    atomicMass: '293',
                  ),
                  ElementBox(
                    atomicNumber: '117',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Ts',
                    elementName: 'Tennessine',
                    atomicMass: '294',
                  ),
                  ElementBox(
                    atomicNumber: '118',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Og',
                    elementName: 'Oganesson',
                    atomicMass: '294',
                  ),
                ],
              ),
              Row(
                children: [
                  ElementBox(
                    atomicNumber: '119',
                    color: Colors.grey.shade300,
                    elementSymbol: 'Uue',
                    elementName: 'Ununennium',
                    atomicMass: '315',
                  ),
                ],
              ),
              Row(
                children: [
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '57',
                    color: Colors.red.shade300,
                    elementSymbol: 'La',
                    elementName: 'Lanthanum',
                    atomicMass: '138.91',
                  ),
                  ElementBox(
                    atomicNumber: '58',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ce',
                    elementName: 'Cerium',
                    atomicMass: '140.12',
                  ),
                  ElementBox(
                    atomicNumber: '59',
                    color: Colors.red.shade300,
                    elementSymbol: 'Pr',
                    elementName: 'Praseodymium',
                    atomicMass: '140.91',
                  ),
                  ElementBox(
                    atomicNumber: '60',
                    color: Colors.red.shade300,
                    elementSymbol: 'Nd',
                    elementName: 'Neodymium',
                    atomicMass: '144.24',
                  ),
                  ElementBox(
                    atomicNumber: '61',
                    color: Colors.red.shade300,
                    elementSymbol: 'Pm',
                    elementName: 'Promethium',
                    atomicMass: '145',
                  ),
                  ElementBox(
                    atomicNumber: '62',
                    color: Colors.red.shade300,
                    elementSymbol: 'Sm',
                    elementName: 'Samarium',
                    atomicMass: '150.36',
                  ),
                  ElementBox(
                    atomicNumber: '63',
                    color: Colors.red.shade300,
                    elementSymbol: 'Eu',
                    elementName: 'Europium',
                    atomicMass: '151.96',
                  ),
                  ElementBox(
                    atomicNumber: '64',
                    color: Colors.red.shade300,
                    elementSymbol: 'Gd',
                    elementName: 'Gadolinium',
                    atomicMass: '157.25',
                  ),
                  ElementBox(
                    atomicNumber: '65',
                    color: Colors.red.shade300,
                    elementSymbol: 'Tb',
                    elementName: 'Terbium',
                    atomicMass: '158.93',
                  ),
                  ElementBox(
                    atomicNumber: '66',
                    color: Colors.red.shade300,
                    elementSymbol: 'Dy',
                    elementName: 'Dysprosium',
                    atomicMass: '162.50',
                  ),
                  ElementBox(
                    atomicNumber: '67',
                    color: Colors.red.shade300,
                    elementSymbol: 'Ho',
                    elementName: 'Holmium',
                    atomicMass: '164.93',
                  ),
                  ElementBox(
                    atomicNumber: '68',
                    color: Colors.red.shade300,
                    elementSymbol: 'Er',
                    elementName: 'Erbium',
                    atomicMass: '167.26',
                  ),
                  ElementBox(
                    atomicNumber: '69',
                    color: Colors.red.shade300,
                    elementSymbol: 'Tm',
                    elementName: 'Thulium',
                    atomicMass: '168.93',
                  ),
                  ElementBox(
                    atomicNumber: '70',
                    color: Colors.red.shade300,
                    elementSymbol: 'Yb',
                    elementName: 'Ytterbium',
                    atomicMass: '173.05',
                  ),
                  ElementBox(
                    atomicNumber: '71',
                    color: Colors.red.shade300,
                    elementSymbol: 'Lu',
                    elementName: 'Lutetium',
                    atomicMass: '174.97',
                  ),
                  const Spacer(),
                ],
              ),
              Row(
                children: [
                  const Spacer(),
                  ElementBox(
                    atomicNumber: '89',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Ac',
                    elementName: 'Actinium',
                    atomicMass: '227',
                  ),
                  ElementBox(
                    atomicNumber: '90',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Th',
                    elementName: 'Thorium',
                    atomicMass: '232.04',
                  ),
                  ElementBox(
                    atomicNumber: '91',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Pa',
                    elementName: 'Protactinium',
                    atomicMass: '231.04',
                  ),
                  ElementBox(
                    atomicNumber: '92',
                    color: Colors.purple.shade300,
                    elementSymbol: 'U',
                    elementName: 'Uranium',
                    atomicMass: '238.03',
                  ),
                  ElementBox(
                    atomicNumber: '93',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Np',
                    elementName: 'Neptunium',
                    atomicMass: '237',
                  ),
                  ElementBox(
                    atomicNumber: '94',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Pu',
                    elementName: 'Plutonium',
                    atomicMass: '244',
                  ),
                  ElementBox(
                    atomicNumber: '95',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Am',
                    elementName: 'Americium',
                    atomicMass: '243',
                  ),
                  ElementBox(
                    atomicNumber: '96',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Cm',
                    elementName: 'Curium',
                    atomicMass: '247',
                  ),
                  ElementBox(
                    atomicNumber: '97',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Bk',
                    elementName: 'Berkelium',
                    atomicMass: '247',
                  ),
                  ElementBox(
                    atomicNumber: '98',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Cf',
                    elementName: 'Californium',
                    atomicMass: '251',
                  ),
                  ElementBox(
                    atomicNumber: '99',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Es',
                    elementName: 'Einsteinium',
                    atomicMass: '252',
                  ),
                  ElementBox(
                    atomicNumber: '100',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Fm',
                    elementName: 'Fermium',
                    atomicMass: '257',
                  ),
                  ElementBox(
                    atomicNumber: '101',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Md',
                    elementName: 'Mendelevium',
                    atomicMass: '258',
                  ),
                  ElementBox(
                    atomicNumber: '102',
                    color: Colors.purple.shade300,
                    elementSymbol: 'No',
                    elementName: 'Nobelium',
                    atomicMass: '259',
                  ),
                  ElementBox(
                    atomicNumber: '103',
                    color: Colors.purple.shade300,
                    elementSymbol: 'Lr',
                    elementName: 'Lawrencium',
                    atomicMass: '266',
                  ),
                  const Spacer(),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ElementBox extends StatelessWidget {
  const ElementBox({
    super.key,
    required this.atomicNumber,
    required this.color,
    required this.elementSymbol,
    required this.elementName,
    required this.atomicMass,
  });

  final String atomicNumber;
  final Color color;
  final String elementSymbol;
  final String elementName;
  final String atomicMass;

  @override
  Widget build(BuildContext context) {
    double deviceSize = MediaQuery.of(context).size.width;
    double boxSize = (deviceSize / 18) - const EdgeInsets.all(0.8).w.horizontal;
    return UnconstrainedBox(
      child: Container(
        width: boxSize,
        margin: const EdgeInsets.all(0.8).w,
        padding: const EdgeInsets.all(0.1).w,
        decoration: BoxDecoration(
          border: Border.all(
            color: color,
            width: 1.w,
          ),
        ),
        child: Column(
          children: [
            Container(
              alignment: Alignment.centerLeft,
              margin: EdgeInsets.zero,
              child: Text(
                atomicNumber,
                textAlign: TextAlign.left,
                style: TextStyle(
                  color: color,
                  fontSize: 3.sp,
                  shadows: [
                    BoxShadow(
                      color: color,
                      blurRadius: 2.r,
                    ),
                  ],
                ),
              ),
            ),
            Text(
              elementSymbol,
              textAlign: TextAlign.left,
              style: TextStyle(
                color: color,
                fontSize: 8.sp,
                fontWeight: FontWeight.w900,
                shadows: [
                  BoxShadow(
                    color: color,
                    blurRadius: 2.r,
                  ),
                ],
              ),
            ),
            FittedBox(
              child: Text(
                elementName,
                textAlign: TextAlign.left,
                style: TextStyle(
                  color: color,
                  fontSize: 3.sp,
                  shadows: [
                    BoxShadow(
                      color: color,
                      blurRadius: 5.r,
                    ),
                  ],
                ),
              ),
            ),
            Text(
              atomicMass,
              textAlign: TextAlign.left,
              style: TextStyle(
                color: color,
                fontSize: 2.5.sp,
                shadows: [
                  BoxShadow(
                    color: color,
                    blurRadius: 5.r,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
